### ISSUE TITLE
Only static members can be accessed in initializers.

### ISSUE THREAD

**Issue by Flutter-Stack** [JamalBelilet/steps#1]
I Am getting below error when I am trying to implement step form with radio button.
"Only static members can be accessed in initializers." 

class _CreateAudienceState extends State<CreateAudience> {
  String _radioValue = "";
  _handleRadioValueChange(String value) {
    setState(() {
      _radioValue = value;
      debugPrint(_radioValue); //Debug the choice in console
    });
  }
  @override
  void initState() {
    super.initState();
  }
  @override
  void dispose() {
    _focusNode.dispose();
    super.dispose();
  }
  List<Step> steps = [
    new Step(
        title: const Text('Audience Name'),
        //subtitle: const Text('Enter your name'),
        isActive: true,
        //state: StepState.error,
        state: StepState.indexed,
        content: Column(
          children: [
        new Text(
              'Gender',
              style: new TextStyle(
                fontWeight: FontWeight.bold,
                fontSize: 18.0,
              ),
            ),
            new Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
              new Radio(
                  value: "male",
                  groupValue: _radioValue,
                  onChanged: _handleRadioValueChange,
                ),
                new Radio(
                  value: "female",
                  groupValue: _radioValue,
                  onChanged: _handleRadioValueChange,
                ),
                new Radio(
                  value: "all",
                  groupValue: _radioValue,
                  onChanged: _handleRadioValueChange,
                ),
              ],
            ),
         ]);
Error showing for _radioValue and _handleRadioValueChange.

Please suggestion how to create step form with radio button form. 
Thank you Everyone for the answers in advance.

**Comment by JamalBelilet** [comment]
The problem is not with the package, you're facing this error because you're trying to access some class properties (_radioValue and _handleRadioValueChange) before initializing all the of them (steps), what I'd do to solve such issue is to initialize all the properties needed for the steps array (_radioValue and _handleRadioValueChange) and than initialize the steps array within the initState method.

The code will look like:

```dart
String _radioValue = "";
List steps = [];
_handleRadioValueChange(String value) {
  setState(() {
    _radioValue = value;
    debugPrint(_radioValue); //Debug the choice in console
  });
}

void initState() {
  super.initState();
  steps = [
    Step(
      title: const Text('Audience Name'),
      isActive: true,
      state: StepState.indexed,
      content: Column(
        children: [
          Text(
              'Gender',
              style: TextStyle(
              fontWeight: FontWeight.bold,
              fontSize: 18.0,
            ),
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Radio(
                value: "male",
                groupValue: _radioValue,
                onChanged: _handleRadioValueChange,
              ),
              Radio(
                value: "female",
                groupValue: _radioValue,
                onChanged: _handleRadioValueChange,
              ),
              Radio(
                value: "all",
                groupValue: _radioValue,
                onChanged: _handleRadioValueChange,
              ),
            ],
          ),
        ],
      ),
    ),
  ];
  setState((){})
}
```
